# -*- coding: utf-8 -*-
"""Despliegue_Streamlit_Vinos_DOA_FTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNDJNQ8jYuCz3iOKClOJ4wNsetMcKCpQ

# Despliegue Streamlit Vinos

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-cla-vinos.pkl'
modelo, labelencoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))
#modelo

#Cargamos los datos futuros
#data = pd.read_csv("ataque_corazon-datosFuturos.csv")
#data.head()

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.set_page_config(page_title="Predicción de Calidad de Vinos", page_icon="🍷", layout="centered")

st.markdown("""
    <style>
    /* Fondo: copa de tinto con brillo dorado arriba */
    .stApp {
        background:
            radial-gradient(ellipse at 15% 0%, rgba(227,181,91,0.18) 0%, transparent 45%),
            radial-gradient(ellipse at 100% 100%, rgba(196,69,105,0.25) 0%, transparent 50%),
            linear-gradient(165deg, #1a0710 0%, #3d0f22 55%, #5c1631 100%);
        color:#f8ecef;
    }
    [data-testid="stHeader"] { background: transparent; }

    /* Título con degradado oro -> rosado */
    h1 {
        background: linear-gradient(90deg, #f3d48a 0%, #e3b55b 40%, #e8879c 100%);
        -webkit-background-clip: text; background-clip: text;
        -webkit-text-fill-color: transparent; font-weight:800 !important;
    }
    h2, h3 { color:#f3d48a !important; font-weight:700 !important; }
    p, .stCaption, [data-testid="stCaptionContainer"] { color:#e9cdd4 !important; }
    label, .stSelectbox label, .stSlider label { color:#f8ecef !important; font-weight:600 !important; }

    /* Columnas como tarjetas de vidrio */
    [data-testid="stColumn"], [data-testid="column"] {
        background: rgba(255,255,255,0.04);
        border: 1px solid rgba(227,181,91,0.22);
        border-radius: 16px; padding: 1rem 1.1rem;
        box-shadow: 0 10px 30px rgba(0,0,0,0.25);
    }

    /* Tabla */
    [data-testid="stDataFrame"] {
        border: 1px solid rgba(227,181,91,0.25); border-radius: 12px; overflow: hidden;
    }

    /* Botón dorado */
    div.stButton > button {
        background: linear-gradient(90deg, #c8922f 0%, #e3b55b 50%, #f3d48a 100%);
        color:#2a0a16; font-weight:800; letter-spacing:0.3px;
        border:none; border-radius:14px; padding:0.7rem 1.4rem; width:100%;
        transition: transform .15s ease, box-shadow .15s ease;
    }
    div.stButton > button:hover {
        color:#1a0710; transform: translateY(-2px);
        box-shadow:0 10px 24px rgba(227,181,91,0.40);
    }

    /* Tarjetas de resultado */
    .resultado {
        border-radius: 16px; padding: 1.2rem 1.4rem; margin: 0.8rem 0;
        font-size: 1.15rem; font-weight: 700; text-align: center;
    }
    .resultado .prob { display:block; font-size:0.95rem; font-weight:500; opacity:0.85; margin-top:0.3rem; }
    .resultado.buena {
        background: linear-gradient(135deg, rgba(143,184,92,0.25), rgba(227,181,91,0.20));
        border: 1px solid #a9c97a; color:#e6f3d3;
    }
    .resultado.mala {
        background: linear-gradient(135deg, rgba(196,69,105,0.30), rgba(90,20,40,0.35));
        border: 1px solid #e8879c; color:#ffdfe6;
    }
    </style>
""", unsafe_allow_html=True)

st.title('🍷 Predicción de Calidad de Vinos')
st.caption('Modelo Red Neuronal (MLP) — ingresa las características fisicoquímicas del vino')

#Tipo de vino
tipo = st.selectbox('Tipo de vino', ['blanco', 'tinto'])

#Variables numéricas en dos columnas (rangos min-max de los datos de entrenamiento, valor inicial = mediana)
col1, col2 = st.columns(2)

with col1:
    st.subheader('🧪 Acidez y azúcar')
    fixed_acidity = st.slider('Acidez fija (fixed acidity)', min_value=3.8, max_value=15.9, value=6.9, step=0.1)
    volatile_acidity = st.slider('Acidez volátil (volatile acidity)', min_value=0.08, max_value=1.58, value=0.29, step=0.01)
    citric_acid = st.slider('Ácido cítrico (citric acid)', min_value=0.0, max_value=1.66, value=0.31, step=0.01)
    residual_sugar = st.slider('Azúcar residual (residual sugar)', min_value=0.6, max_value=65.8, value=2.9, step=0.1)
    chlorides = st.slider('Cloruros (chlorides)', min_value=0.009, max_value=0.611, value=0.046, step=0.001, format="%.3f")
    pH = st.slider('pH', min_value=2.72, max_value=4.01, value=3.21, step=0.01)

with col2:
    st.subheader('⚗️ Sulfitos, densidad y alcohol')
    free_sulfur_dioxide = st.slider('Dióxido de azufre libre (free sulfur dioxide)', min_value=1.0, max_value=289.0, value=29.0, step=1.0)
    total_sulfur_dioxide = st.slider('Dióxido de azufre total (total sulfur dioxide)', min_value=6.0, max_value=440.0, value=120.0, step=1.0)
    density = st.slider('Densidad (density)', min_value=0.9871, max_value=1.0390, value=0.9944, step=0.0001, format="%.4f")
    sulphates = st.slider('Sulfatos (sulphates)', min_value=0.22, max_value=2.0, value=0.5, step=0.01)
    alcohol = st.slider('Alcohol (% vol)', min_value=8.0, max_value=14.9, value=10.4, step=0.1)


#Dataframe
predictoras_numericas = ['fixed acidity', 'volatile acidity', 'citric acid',
                         'residual sugar', 'chlorides', 'free sulfur dioxide',
                         'total sulfur dioxide', 'density', 'pH', 'sulphates',
                         'alcohol']

datos = [[fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides,
          free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol, tipo]]
data = pd.DataFrame(datos, columns=predictoras_numericas + ['tipo']) #Dataframe con los mismos nombres de variables

st.subheader('📋 Datos ingresados')
st.dataframe(data)

# Recordar medida de desempeño del modelo (validación cruzada, 10 folds)

st.warning("El modelo tiene una exactitud aproximada del 76% (F1 macro: 0.74 en validación cruzada)")

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['tipo'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes (queda solo tipo_tinto, igual que en el entrenamiento)
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#Como el modelo final es una Red Neuronal SÍ se normaliza
data_preparada[predictoras_numericas]= min_max_scaler.transform(data_preparada[predictoras_numericas])
data_preparada.head()

"""# Predicción"""


#Mostrar la predicción en la interfaz al presionar el botón
if st.button('🔍 Predecir calidad'):

    #Hacemos la predicción con la Red Neuronal
    Y_pred = modelo.predict(data_preparada)

    #Se convierte 0/1 a la etiqueta original (Buena/Mala)
    Y_pred_etiqueta = labelencoder.inverse_transform(Y_pred)
    data['Prediccion'] = Y_pred_etiqueta

    #Probabilidad de la clase predicha
    probabilidad = modelo.predict_proba(data_preparada)[0].max()

    #Resultado en color
    if Y_pred_etiqueta[0] == 'Buena':
        st.markdown(f'<div class="resultado buena">🍇 El modelo predice que el vino es de calidad BUENA'
                    f'<span class="prob">{probabilidad:.0%} de probabilidad</span></div>', unsafe_allow_html=True)
        st.balloons()
    else:
        st.markdown(f'<div class="resultado mala">⚠️ El modelo predice que el vino es de calidad MALA'
                    f'<span class="prob">{probabilidad:.0%} de probabilidad</span></div>', unsafe_allow_html=True)

    #Tabla con la predicción
    st.dataframe(data)

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 8% (mape: error porcentual)")

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['tipo'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#Como el modelo final es Random Forest (árboles) NO se normaliza -> se deja comentado
#data_preparada[['age','avg_glucose_level']]= min_max_scaler.transform(data_preparada[['age','avg_glucose_level']])
#data_preparada.head()

"""# Predicción"""

#Hacemos la predicción con el Random Forest
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

#Se convierte 0/1 a la etiqueta original (No/Yes)
Y_pred_etiqueta = labelencoder.inverse_transform(Y_pred)
data['Prediccion']=Y_pred_etiqueta
data.head()