# -*- coding: utf-8 -*-
"""Despliegue_Streamlit_Vinos_DOA_FTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PNDJNQ8jYuCz3iOKClOJ4wNsetMcKCpQ

# Despliegue Streamlit Vinos

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros: normalizar, dummies
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-cla-vinos.pkl'
modelo, labelencoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))
#modelo

#Cargamos los datos futuros
#data = pd.read_csv("ataque_corazon-datosFuturos.csv")
#data.head()

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.set_page_config(page_title="Predicción de Calidad de Vinos", page_icon="🍷", layout="centered")

st.markdown("""
    <style>
    .stApp { background: linear-gradient(160deg, #2b0a14 0%, #5a1428 50%, #7b1e3a 100%); color:#fbeff2; }
    h1, h2, h3, .stCaption, p { color:#fbeff2 !important; }
    label, .stSelectbox label, .stSlider label { color:#f7dce3 !important; font-weight:600 !important; }
    div.stButton > button {
        background: linear-gradient(90deg, #c9a227 0%, #f3d77a 100%);
        color:#2b0a14; font-weight:700; border:none; border-radius:12px; padding:0.6rem 1.4rem; width:100%;
    }
    div.stButton > button:hover { box-shadow:0 8px 20px rgba(243,215,122,0.35); color:#000; }
    </style>
""", unsafe_allow_html=True)

st.title('🍷 Predicción de Calidad de Vinos')
st.caption('Modelo Red Neuronal (MLP) — ingresa las características fisicoquímicas del vino')

#Tipo de vino
tipo = st.selectbox('Tipo de vino', ['blanco', 'tinto'])

#Variables numéricas en dos columnas (rangos min-max de los datos de entrenamiento, valor inicial = mediana)
col1, col2 = st.columns(2)

with col1:
    st.subheader('🧪 Acidez y azúcar')
    fixed_acidity = st.slider('Acidez fija (fixed acidity)', min_value=3.8, max_value=15.9, value=6.9, step=0.1)
    volatile_acidity = st.slider('Acidez volátil (volatile acidity)', min_value=0.08, max_value=1.58, value=0.29, step=0.01)
    citric_acid = st.slider('Ácido cítrico (citric acid)', min_value=0.0, max_value=1.66, value=0.31, step=0.01)
    residual_sugar = st.slider('Azúcar residual (residual sugar)', min_value=0.6, max_value=65.8, value=2.9, step=0.1)
    chlorides = st.slider('Cloruros (chlorides)', min_value=0.009, max_value=0.611, value=0.046, step=0.001, format="%.3f")
    pH = st.slider('pH', min_value=2.72, max_value=4.01, value=3.21, step=0.01)

with col2:
    st.subheader('⚗️ Sulfitos, densidad y alcohol')
    free_sulfur_dioxide = st.slider('Dióxido de azufre libre (free sulfur dioxide)', min_value=1.0, max_value=289.0, value=29.0, step=1.0)
    total_sulfur_dioxide = st.slider('Dióxido de azufre total (total sulfur dioxide)', min_value=6.0, max_value=440.0, value=120.0, step=1.0)
    density = st.slider('Densidad (density)', min_value=0.9871, max_value=1.0390, value=0.9944, step=0.0001, format="%.4f")
    sulphates = st.slider('Sulfatos (sulphates)', min_value=0.22, max_value=2.0, value=0.5, step=0.01)
    alcohol = st.slider('Alcohol (% vol)', min_value=8.0, max_value=14.9, value=10.4, step=0.1)


#Dataframe
predictoras_numericas = ['fixed acidity', 'volatile acidity', 'citric acid',
                         'residual sugar', 'chlorides', 'free sulfur dioxide',
                         'total sulfur dioxide', 'density', 'pH', 'sulphates',
                         'alcohol']

datos = [[fixed_acidity, volatile_acidity, citric_acid, residual_sugar, chlorides,
          free_sulfur_dioxide, total_sulfur_dioxide, density, pH, sulphates, alcohol, tipo]]
data = pd.DataFrame(datos, columns=predictoras_numericas + ['tipo']) #Dataframe con los mismos nombres de variables

st.subheader('📋 Datos ingresados')
st.dataframe(data)

# Recordar medida de desempeño del modelo (validación cruzada, 10 folds)

st.warning("El modelo tiene una exactitud aproximada del 76% (F1 macro: 0.74 en validación cruzada)")

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['tipo'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes (queda solo tipo_tinto, igual que en el entrenamiento)
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#Como el modelo final es una Red Neuronal SÍ se normaliza
data_preparada[predictoras_numericas]= min_max_scaler.transform(data_preparada[predictoras_numericas])
data_preparada.head()

"""# Predicción"""


#Mostrar la predicción en la interfaz al presionar el botón
if st.button('🔍 Predecir calidad'):

    #Hacemos la predicción con la Red Neuronal
    Y_pred = modelo.predict(data_preparada)

    #Se convierte 0/1 a la etiqueta original (Buena/Mala)
    Y_pred_etiqueta = labelencoder.inverse_transform(Y_pred)
    data['Prediccion'] = Y_pred_etiqueta

    #Probabilidad de la clase predicha
    probabilidad = modelo.predict_proba(data_preparada)[0].max()

    #Resultado en color
    if Y_pred_etiqueta[0] == 'Buena':
        st.success(f'🍇 El modelo predice que el vino es de calidad BUENA ({probabilidad:.0%} de probabilidad)')
        st.balloons()
    else:
        st.error(f'⚠️ El modelo predice que el vino es de calidad MALA ({probabilidad:.0%} de probabilidad)')

    #Tabla con la predicción
    st.dataframe(data)

data

# Recordar medida de error del modelo

st.warning("El modelo tiene un error del 8% (mape: error porcentual)")

#Se realiza la preparación de datos
data_preparada=data.copy()

#En despliegue drop_first= False
data_preparada = pd.get_dummies(data_preparada, columns=['tipo'], drop_first=False, dtype=int)
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza para predecir con Knn, Red, SVM, Reg
#En los despliegues no se llama fit
#Como el modelo final es Random Forest (árboles) NO se normaliza -> se deja comentado
#data_preparada[['age','avg_glucose_level']]= min_max_scaler.transform(data_preparada[['age','avg_glucose_level']])
#data_preparada.head()

"""# Predicción"""

#Hacemos la predicción con el Random Forest
Y_pred = modelo.predict(data_preparada)
print(Y_pred)

#Se convierte 0/1 a la etiqueta original (No/Yes)
Y_pred_etiqueta = labelencoder.inverse_transform(Y_pred)
data['Prediccion']=Y_pred_etiqueta
data.head()